steps:
- name: gcr.io/cloud-builders/npm
  args: ['install']
- name: gcr.io/cloud-builders/npm
  args: ['test']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: ['./scripts/prod-deploy.sh']